package model;
// by JeromeNL :)
public class DieSupply {
	
	
	
	public void getStartDies() {
		// get 90 random dies from database
	}
	
	public void amountDecider() {
		// method gives 50, 70 or 90 dies (generated by getStartDies())
		// 2 players = 50 dies
		// 3 players = 70 dies
		// 4 players = 90 dies
		
	}
	

}
